ArenaLive.defaults = {
  unitFrames = {
    left = {
      enabled = true,
      configMode = false,
      width = 192,
      height = 64,
      anchor = {
        point = "CENTER",
        x = 0,
        y = 0,
      },
      tooltip = DeliUnitFrames.classes.AbstractUnitFrame.TooltipModes.NEVER,
      leftClick = "target",
      rightClick = "togglemenu",
      components = {
        HealthBar = {
          enabled = true,
          anchor = {
            relativeTo = "UnitFrame",
            point = "TOPRIGHT",
            relativePoint = "TOPRIGHT",
            x = 0,
            y = 0,
          },
          width = 128,
          height = 42,
          texture = "Interface\\TargetingFrame\\UI-StatusBar",
          colorMode = DeliUnitFrames.classes.HealthBar.ColorModes.CLASS,
        },
        PowerBar = {
          enabled = true,
          anchor = {
            relativeTo = "HealthBar",
            point = "TOPLEFT",
            relativePoint = "BOTTOMLEFT",
            x = 0,
            y = -1,
          },
          width = 128,
          height = 21,
          texture = "Interface\\TargetingFrame\\UI-StatusBar",
        },
        ClassIcon = {
          enabled = true,
          anchor = {
            relativeTo = "UnitFrame",
            point = "TOPLEFT",
            relativePoint = "TOPLEFT",
            x = 0,
            y = 0,
          },
          width = 64,
          height = 64,
        },
        BuffFrame = {
          enabled = true,
          anchor = {
            relativeTo = "PowerBar",
            point = "TOPLEFT",
            relativePoint = "BOTTOMLEFT",
            x = 0,
            y = -1,
          },
          columns = 5,
          maxIndicators = 10,
          offset = 2,
          filter = "",
          iconSize = 24,
          showCooldownText = false,
        },
        DebuffFrame = {
          enabled = true,
          anchor = {
            relativeTo = "BuffFrame",
            point = "TOPLEFT",
            relativePoint = "BOTTOMLEFT",
            x = 0,
            y = -2,
          },
          columns = 5,
          maxIndicators = 10,
          offset = 2,
          filter = "",
          iconSize = 24,
          showCooldownText = false,
        },
      },
    },
  },
};
